# Generated by Django 2.0.1 on 2018-01-08 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('city', models.CharField(max_length=50, verbose_name='ciudad')),
                ('description', models.CharField(max_length=200, verbose_name='descripcion')),
                ('hour_start', models.TimeField(verbose_name='hora comienzo')),
                ('hour_end', models.TimeField(verbose_name='hora fin')),
            ],
            options={
                'verbose_name': 'descuento',
                'verbose_name_plural': 'descuentos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('image', models.URLField()),
                ('days', models.IntegerField()),
                ('altitude_average', models.IntegerField()),
                ('description', models.CharField(max_length=200, verbose_name='descripcion')),
                ('include', models.CharField(max_length=200, verbose_name='incluye')),
                ('not_include', models.CharField(max_length=200, verbose_name='no incluye')),
                ('private_price', models.CharField(max_length=50, verbose_name='precio privado')),
                ('shared_price', models.CharField(max_length=50, verbose_name='precio compartido')),
                ('difficulty', models.CharField(max_length=50, verbose_name='dificultad')),
                ('spa_trip', models.CharField(max_length=150, verbose_name='spa excursion')),
                ('hour_start', models.TimeField(verbose_name='hora inicio')),
                ('hour_end', models.TimeField(verbose_name='hora inicio')),
                ('distance_total', models.CharField(max_length=50, verbose_name='distancia total')),
                ('recommended_for', models.CharField(max_length=200, verbose_name='recomendado para')),
                ('consideration', models.CharField(max_length=200, verbose_name='consideraciones')),
                ('state', models.BooleanField(default=True)),
                ('visit', models.IntegerField()),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Destiny')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Type_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('model', models.CharField(max_length=200, verbose_name='modelo')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de servicio',
                'verbose_name_plural': 'tipos de servicio',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Type_service'),
        ),
    ]
