# Generated by Django 2.0 on 2018-01-08 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.CharField(max_length=150, verbose_name='usuario')),
                ('skype', models.CharField(max_length=150, verbose_name='skype')),
                ('country', models.CharField(max_length=25, verbose_name='pais')),
                ('city', models.CharField(max_length=25, verbose_name='ciudad')),
            ],
            options={
                'verbose_name_plural': 'clientes',
                'verbose_name': 'cliente',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Detail_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sale_price', models.CharField(max_length=50, verbose_name='precio venta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cantidad')),
                ('igv', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IGV')),
            ],
            options={
                'verbose_name_plural': 'servicios',
                'verbose_name': 'servicio',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Discount_offert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='nombre oferta')),
                ('offert_code', models.CharField(max_length=20, verbose_name='codigo promocion')),
                ('description', models.CharField(max_length=200, verbose_name='descripcion')),
                ('date_limit', models.DateTimeField(verbose_name='fecha limite')),
                ('use_number', models.IntegerField(verbose_name='numero de usuario')),
            ],
            options={
                'verbose_name_plural': 'descuentos',
                'verbose_name': 'descuento',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_sale', models.DateTimeField()),
                ('state', models.BooleanField(verbose_name='estado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='pagos.Client')),
            ],
            options={
                'verbose_name_plural': 'ventas',
                'verbose_name': 'venta',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='detail_sale',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuento', to='pagos.Discount_offert'),
        ),
        migrations.AddField(
            model_name='detail_sale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='pagos.Sale'),
        ),
        migrations.AddField(
            model_name='detail_sale',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='servicio.Service'),
        ),
    ]
