# Generated by Django 2.0 on 2018-01-08 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title_seo', models.CharField(max_length=100, verbose_name='titulo seo')),
                ('description_seo', models.CharField(max_length=200, verbose_name='descripcion seo')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('sub_title', models.CharField(max_length=200, verbose_name='subtitulo')),
                ('description', models.CharField(max_length=200, verbose_name='descripcion')),
                ('content', models.CharField(max_length=200, verbose_name='contenido')),
                ('author', models.CharField(max_length=200, verbose_name='autor')),
                ('image1', models.URLField(verbose_name='imagen 1')),
                ('image2', models.URLField(verbose_name='imagen 2')),
                ('image3', models.URLField(verbose_name='imagen 3')),
            ],
            options={
                'verbose_name_plural': 'blogs',
                'verbose_name': 'blog',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('model', models.CharField(max_length=200, verbose_name='modelos')),
                ('name_spa', models.CharField(max_length=100, verbose_name='nombre spa')),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'verbose_name': 'categoria',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'tags',
                'verbose_name': 'tag',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
        ),
    ]
